In [ ]:
# pip install pickle
import pickle
import pandas as pd

In [1]:
# pandas 라이브러리가 2.0.0 이상은 되어야 되는것 같습니다.
print(pd.__version__)

NameError: name 'pd' is not defined

In [ ]:
# pandas 업그레이드
pip install --upgrade pandas --user

In [2]:
with open('cmc_data_final2_with_stable.pickle', 'rb') as file:
    # pickle 객체를 로드합니다.
    data = pickle.load(file)

data

C:\Users\user\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

              date  coin_id      name   symbol        open        high  \
0       2013-04-28        1   Bitcoin      BTC  135.300003  135.979996
1       2013-04-29        1   Bitcoin      BTC  134.444000  147.488007
2       2013-04-30        1   Bitcoin      BTC  144.000000  146.929993
3       2013-05-01        1   Bitcoin      BTC  139.000000  139.889999
4       2013-05-02        1   Bitcoin      BTC  116.379997  125.599998
...            ...      ...       ...      ...         ...         ...
7693214 2023-08-24    27900  Ethera X  ETHERAX    0.002020    0.002095
7693215 2023-08-25    27900  Ethera X  ETHERAX    0.001620    0.001623
7693216 2023-08-26    27900  Ethera X  ETHERAX    0.001525    0.002047
7693217 2023-08-27    27900  Ethera X  ETHERAX    0.002042    0.002228
7693218 2023-08-28    27900  Ethera X  ETHERAX    0.002227    0.002227

                low       close      vol        mktcap  \
0        132.100006  134.210007     0.00  1.488567e+09
1        134.000000  144.539993     0.00  1.603769e+09
2        134.050003  139.000000     0.00  1.542813e+09
3        107.720001  116.989998     0.00  1.298955e+09
4         92.281898  105.209999     0.00  1.168517e+09
...             ...         ...      ...           ...
7693214    0.001612    0.001620  4160.03  0.000000e+00
7693215    0.001511    0.001525   795.34  0.000000e+00
7693216    0.001514    0.002042  3408.42  0.000000e+00
7693217    0.001763    0.002228  4788.38  0.000000e+00
7693218    0.001833    0.001833  2693.94  0.000000e+00

                         timehigh                   timelow
0        2013-04-28T18:50:02.000Z  2013-04-28T20:15:02.000Z
1        2013-04-29T13:15:01.000Z  2013-04-29T05:20:01.000Z
2        2013-04-30T08:25:02.000Z  2013-04-30T18:55:01.000Z
3        2013-05-01T00:15:01.000Z  2013-05-01T19:55:01.000Z
4        2013-05-02T14:25:01.000Z  2013-05-02T14:30:02.000Z
...                           ...                       ...
7693214  2023-08-24T09:10:00.000Z  2023-08-24T23:20:00.000Z
7693215  2023-08-25T02:32:00.000Z  2023-08-25T17:50:00.000Z
7693216  2023-08-26T22:30:00.000Z  2023-08-26T17:42:00.000Z
7693217  2023-08-27T23:59:00.000Z  2023-08-27T21:56:00.000Z
7693218  2023-08-28T00:00:00.000Z  2023-08-28T23:59:00.000Z

[7693219 rows x 12 columns]

In [4]:
data

,date,coin_id,name,symbol,open,high,low,close,vol,mktcap,timehigh,timelow
0,2013-04-28,1,Bitcoin,BTC,135.300003,135.979996,132.100006,134.210007,0.00,1.488567e+09,2013-04-28T18:50:02.000Z,2013-04-28T20:15:02.000Z
1,2013-04-29,1,Bitcoin,BTC,134.444000,147.488007,134.000000,144.539993,0.00,1.603769e+09,2013-04-29T13:15:01.000Z,2013-04-29T05:20:01.000Z
2,2013-04-30,1,Bitcoin,BTC,144.000000,146.929993,134.050003,139.000000,0.00,1.542813e+09,2013-04-30T08:25:02.000Z,2013-04-30T18:55:01.000Z
3,2013-05-01,1,Bitcoin,BTC,139.000000,139.889999,107.720001,116.989998,0.00,1.298955e+09,2013-05-01T00:15:01.000Z,2013-05-01T19:55:01.000Z
4,2013-05-02,1,Bitcoin,BTC,116.379997,125.599998,92.281898,105.209999,0.00,1.168517e+09,2013-05-02T14:25:01.000Z,2013-05-02T14:30:02.000Z
...,...,...,...,...,...,...,...,...,...,...,...,...
7693214,2023-08-24,27900,Ethera X,ETHERAX,0.002020,0.002095,0.001612,0.001620,4160.03,0.000000e+00,2023-08-24T09:10:00.000Z,2023-08-24T23:20:00.000Z
7693215,2023-08-25,27900,Ethera X,ETHERAX,0.001620,0.001623,0.001511,0.001525,795.34,0.000000e+00,2023-08-25T02:32:00.000Z,2023-08-25T17:50:00.000Z
7693216,2023-08-26,27900,Ethera X,ETHERAX,0.001525,0.002047,0.001514,0.002042,3408.42,0.000000e+00,2023-08-26T22:30:00.000Z,2023-08-26T17:42:00.000Z
7693217,2023-08-27,27900,Ethera X,ETHERAX,0.002042,0.002228,0.001763,0.002228,4788.38,0.000000e+00,2023-08-27T23:59:00.000Z,2023-08-27T21:56:00.000Z
7693218,2023-08-28,27900,Ethera X,ETHERAX,0.002227,0.002227,0.001833,0.001833,2693.94,0.000000e+00,2023-08-28T00:00:00.000Z,2023-08-28T23:59:00.000Z