In [2]:
import numpy as np
import requests
from bs4 import BeautifulSoup
import time
import re
import pandas as pd
import os
import matplotlib.pyplot as plt

### 통합데이터 read

In [8]:
df = pd.read_excel('이미지.xlsx')
df = df.transpose()
df.to_csv('이미지.csv', encoding='utf-8-sig')

In [9]:
df = pd.read_csv('KRW_cryptos_krw_pyupbit.csv')
df

,date,open,high,low,close,volume,value,currency
0,2017-09-25 09:00:00,4201000.0,4333000.0,4175000.0,4322000.0,1.324848e+02,5.602146e+08,KRW-BTC
1,2017-09-26 09:00:00,4317000.0,4418000.0,4311000.0,4321000.0,2.278834e+01,9.950724e+07,KRW-BTC
2,2017-09-27 09:00:00,4322000.0,4677000.0,4318000.0,4657000.0,3.226966e+01,1.448276e+08,KRW-BTC
3,2017-09-28 09:00:00,4657000.0,4772000.0,4519000.0,4586000.0,8.058824e+01,3.721860e+08,KRW-BTC
4,2017-09-29 09:00:00,4586000.0,4709000.0,4476000.0,4657000.0,5.935237e+01,2.724558e+08,KRW-BTC
...,...,...,...,...,...,...,...,...
168576,2023-09-16 09:00:00,168.0,202.0,164.0,190.0,9.078253e+08,1.699701e+11,KRW-SEI
168577,2023-09-17 09:00:00,190.0,191.0,165.0,166.0,3.286900e+08,5.776295e+10,KRW-SEI
168578,2023-09-18 09:00:00,165.0,172.0,161.0,167.0,1.633393e+08,2.709218e+10,KRW-SEI
168579,2023-09-19 09:00:00,167.0,170.0,162.0,168.0,1.079979e+08,1.795616e+10,KRW-SEI
168580,2023-09-20 09:00:00,168.0,175.0,167.0,171.0,8.458786e+07,1.442943e+10,KRW-SEI

In [10]:
# 'KRW-BTC'에 해당하는 데이터만 필터링
bitcoin = df[df['currency'] == 'KRW-BTC']

# 로그 수익률 계산
bitcoin['수익률'] = np.log(bitcoin['close'] / bitcoin['close'].shift(1))

# 결과 확인
bitcoin.head()

<ipython-input-10-a4916a1c2d10>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bitcoin['수익률'] = np.log(bitcoin['close'] / bitcoin['close'].shift(1))

,date,open,high,low,close,volume,value,currency,수익률
0,2017-09-25 09:00:00,4201000.0,4333000.0,4175000.0,4322000.0,132.484755,5.602146e+08,KRW-BTC,NaN
1,2017-09-26 09:00:00,4317000.0,4418000.0,4311000.0,4321000.0,22.788340,9.950724e+07,KRW-BTC,-0.000231
2,2017-09-27 09:00:00,4322000.0,4677000.0,4318000.0,4657000.0,32.269662,1.448276e+08,KRW-BTC,0.074885
3,2017-09-28 09:00:00,4657000.0,4772000.0,4519000.0,4586000.0,80.588243,3.721860e+08,KRW-BTC,-0.015363
4,2017-09-29 09:00:00,4586000.0,4709000.0,4476000.0,4657000.0,59.352373,2.724558e+08,KRW-BTC,0.015363

In [12]:
bitcoin.to_csv('bitcoin_krw.csv', encoding='utf-8-sig')